# prospector configuration file

---

output-format: grouped

strictness: veryhigh
doc-warnings: false
test-warnings: true
member-warnings: false

ignore-paths:
  - docs
  - src/cffconvert/gcloud/gcloud.py

pyroma:
    run: true

pycodestyle:
  full: true
  disable:
    - E501 # test line length with pylint instead, as that can be disabled per file and/or per line if needed

pylint:
  disable:
    - invalid-name
  full: true
  options:
    max-line-length: 120

pydocstyle:
  disable:
    # Disable because not part of PEP257 official convention:
    # see http://pep257.readthedocs.io/en/latest/error_codes.html
    - D203  # 1 blank line required before class docstring
    - D212  # Multi-line docstring summary should start at the first line
    - D213  # Multi-line docstring summary should start at the second line
    - D404  # First word of the docstring should not be This
